### ISSUE TITLE
Intructions on running it locally

### ISSUE THREAD

**Issue by Sbatra0105** [lwc-soql-builder/lwc-soql-builder#2]
Hi

Could you please elaborate on the instructions locally? Our org has IP restrictions. So I can run this only locally but I am not familiar with JS. It would be very helpful to have detailed instructions. I am not sure of where and how to set the proxy on windows.

Thanks

Shalu

**Comment by atskimura** [comment]
Currently, even if you run LWC SOQL Builder locally, you need to run the proxy server for Salesforce REST API execution on Firebase Cloud Functions.

Please refer to the following URL for instructions on how to run proxies on Firebase Cloud Functions.
https://github.com/lwc-soql-builder/jsforce-ajax-proxy-cloud-functions

I have considered having the Salesforce organization set up CORS to run the REST API without going through a proxy server, but I haven't been able to implement it yet.
