### ISSUE TITLE
Purpose of Google Analytics and gtag call from this tool

### ISSUE THREAD

**Issue by anandabk** [lwc-soql-builder/lwc-soql-builder#29]
Hello Team,

Please confirm what this script does in index.html

    **
    <script async src="https://www.googletagmanager.com/gtag/js?id={$GOOGLE_ANALYTICS_ID}"></script>**

Does it record the pageviews of 

**lwc-soql-builder github site 

or

the salesforce api calls**

**Comment by atskimura** [comment]
Sorry for the late reply.

This code uses Google Analytics only for the purpose of recording page views.
